### ISSUE TITLE
latest version of yfinance breaks with pandas_datareader override(). 

### ISSUE THREAD

**Issue by r-surendiran** [aws-samples/fsi-genai-bootcamp#34]
**Describe bug**
"Part 3 - Construct the tools for the ReACt agent" of the "02_prompt_engineering/3_advanced_techniques.ipynb" notebook fails with latest version of yfinance .

Error: AttributeError: module 'yfinance' has no attribute 'pdr_override'

Updating the requirements.txt to use yfinance version 0.2.40 resolved the issue. yfinance: pandas_datareader support is deprecated and removed from the latest version.

**Comment by szamarin** [comment]
Thanks @r-surendiran! I have fixed the issue
